# Generated by Django 2.2 on 2021-12-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature_products',
            name='pro_desc',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature_products',
            name='prod_cat',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
