# Generated by Django 2.2 on 2021-12-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_auto_20211206_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature_products',
            name='slug',
            field=models.SlugField(default=0, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feature_products',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
