# Generated by Django 2.2 on 2021-12-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_auto_20211206_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature_products',
            name='slug',
        ),
    ]
