# Generated by Django 2.2 on 2021-12-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_remove_feature_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature_products',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
