# Generated by Django 2.2 on 2021-12-07 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_auto_20211206_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature_products',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feature_products',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
