# Generated by Django 2.2 on 2021-12-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_auto_20211206_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature_products',
            name='slug',
        ),
        migrations.AlterField(
            model_name='feature_products',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
