# Generated by Django 2.2 on 2021-12-07 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_auto_20211207_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature_products',
            name='prod_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.category'),
        ),
    ]
